### PR TITLE
Bump splunk add-on-ucc-framework for splunk cloud compatibility

### LINKED ISSUE #182: Addon no longer passes splunk cloud vetting
Looks like the vetting requirements have changed, and now the addon has had its cloud vetting status revoked.
I am no longer able to install `v2.0.17` or `v2.0.16` on a cloud stack.

```json
{
  "description": "Check that the static/ directory does not contains any subdirectories and contains only known file types. Ensure malicious files are not passed off as metadata files.",
  "name": "check_static_directory_file_allow_list",
  "tags": [
    "splunk_appinspect",
    "cloud"
  ],
  "result": "failure",
  "messages": [
    {
      "result": "failure",
      "message": "This file does not appear to be a png image or txt file. Please remove this file from the static directory. File: static/openapi.json",
      "message_filename": "static/openapi.json",
      "message_line": null
    }
  ]
},
```

### PR DESCRIPTION
**Pull request by sanjay900**
Closes #182

Splunk added a vetting rule that disallows json files in the `static` directory. Due to this, `add-on-ucc-framework` has moved `static/openapi.json` to a different directory.

Splunk also seems to have added a rule that fails if you have any `.pyc` files in the addon. Thats the reason why https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/actions/runs/8141235116 failed.

With the updated `add-on-ucc-framework` and `.pyc` files added to the `.uccignore` i was able to successfully vet the addon.

Any version of `add-on-ucc-framework` from `5.34.0` onwards has the fix but we might as well update to the latest

### CODE REVIEW

**Comment by sanjay900** [comment]
I found i also needed to uccignore `.pyc` files to make vetting happy

**Comment by sanjay900** [comment]
@guilhemmarchand Would you be able to look into this please? Its stopping us from being able to update the addon at a bunch of splunk cloud customers.

**Comment by sanjay900** [comment]
@dglauche Have you got write access to this repo? This is breaking the ability to install this addon to splunk cloud, which is causing us issues when we want to set up new splunk stacks.

**Comment by guilhemmarchand** [comment]
@sanjay900 
@dglauche 

My apologises - I could not have time to afford on the app lately - I will take these, verify, and will submit a new release today

**Comment by sanjay900** [comment]
All good I understand, thanks for looking into it!

**Comment by guilhemmarchand** [comment]
Will be addressed properly, *.pyc files to be removed during the automated build, requirements.txt isn't the issue and is being reviewed.

**Comment by guilhemmarchand** [comment]
@sanjay900
@dglauche

Release 2.0.18 has been published today and should pass Cloud vetting!

**Comment by sanjay900** [comment]
Thanks for sorting that, now we just play the waiting game while we wait for it to pass vetting on splunkbase :)

**Pull request closed without merging**
