### PR TITLE
Don't deduplicate specified JIRA status categories

### LINKED ISSUE #33: Suggestion: don't deduplicate closed issues
Firstly, thanks for writing this add-on, it looks really helpful!

I'd like to suggest an improvement. It would be really helpful for us to have this add-on only de-duplicate the issue for certain statuses. i.e. de-duplicate an open issue, but don't de-duplicate a closed one. I suspect you'd want to have the user who is setting up the alert choose which statuses to de-duplicate.

The actual logic to manage this seems like it would be fairly straight-forward and fit in here: https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/blob/36c4d3f3a1c19a749e84508f2fbb90e685672bfd/TA-jira-service-desk-simple-addon/bin/ta_jira_service_desk_simple_addon/modalert_jira_service_desk_helper.py#L398 The code could inspect the field `status.statusCategory.name` from the result from calling `jira_url + "/" + str(jira_backlog_key)`. 

I haven't looked further on adding a list of statuses to the alert page, but I imagine this would be done in a similar way that other data is added to the alert page.

If I find some time in the next few weeks, this is something I'd like to contribute to. Otherwise it would be a great improvement if you have time!

### PR DESCRIPTION
**Pull request by jacobappleton-orbis**
This should resolve #33.

I've tested locally, and it works as expected.

I can't find any contribution guidelines in the repository. Please let me know if there's anything else I should do.

### CODE REVIEW

**Comment by guilhemmarchand** [comment]
Note: will create contributiion guidelines

**Comment by jacobappleton-orbis** [comment]
It seems like it would be nice to break down modalert_jira_service_desk_helper.py a little and introduce unit tests at some point. It took me a few goes to get right because I kept breaking the dedup functionality :)

Perhaps a good idea for a future contribution.

**Comment by guilhemmarchand** [comment]
I totally agree.
The initial version was much simpler, thus features added over time made it become much more complex, splitting the functionalities would be welcome

**Comment by guilhemmarchand** [comment]
Note: When adding new fields on an existing AoB based Add-on (Add-on built with Addon Builder), the field needs to be added to README/*.spec file, otherwise Appinspect will fail and Cloud vetting would get refused.

**Comment by jacobappleton-orbis** [comment]
I can update that now.

**Comment by jacobappleton-orbis** [comment]
That should be in the spec file now.

**Comment by guilhemmarchand** [comment]
@jacobappleton-orbis Have a look in https://github.com/guilhemmarchand/TA-jira-service-desk-simple-addon/issues/33 I've put more information about the current status.

My fault since I didn't integreate a contribute design, but I am working against the testing branch before pushing to master, this PR would conflict as there has been other commits in the meantime, plus our different approach for the same feature ;-)

But we're near the same state now, need to choose between the list of statuses / status categories approach

**Comment by guilhemmarchand** [comment]
@jacobappleton-orbis As discussed earlier, the logic is for the the most part of it included in the version 1.0.19, thanks a thousand for your great inputs and your great help!

**Pull request closed without merging**
