### PR TITLE
Enhancement: jirarest supports additional method for extended JIRA integration

### PR DESCRIPTION
**Pull request by remg427**
Hello,
first thank you for developing this fantastic TA. very well designed, done and documented. 
I use it a lot to create JIRA issues from notable events and alert action works well for this.
Though I would need jirarest to support more method so JIRA rest API endpoints can be used from Splunk to manage issues. My goal is to have a dashboard to abnalyse notable event and to be able to update JIRA issue directly from it without switching nor copy/paste.

Ideally it would be good to have this command as a streaming command so it can be used in an SPL following this simple use case.
- query Splunk to get some data
- format data under field json_request
- call jira API | jirarest target=  method=<GET|DELETE|POST|PUT>
but it will be manageable if it stays a generating command.

So I don't know if you consider PR but here in short what I would like. I am going to test it anyway on my side.

### CODE REVIEW

**Comment by guilhemmarchand** [comment]
Hi @remg427 !

Thank you very much for your compliments, these are very much appreciated!
Wow, this looks fantastic, I was planning actually to extend the jirarest custom command to allow much more integration with JIRA, this work was actually a first step for some advanced interactions so your contribution is more than welcome.

I was planning some of these exact same level of features (which I did for TrackMe in a different style: https://trackme.readthedocs.io/en/latest/rest_api_reference.html)

So that looks really amazing, let me a few days to review and make sure there aren't any defects, and I will be happy to merge and publish.

Again, thanks a lot and let's keep in touch ;-)

**Comment by remg427** [comment]
Thanks,

You are welcome.
Thanks a lot for pointing to  trackme. How comes i have missed it until now.

This look amazing and impressive. I am facing this problem at $dayjob and i am going to install it right away. You made my day brighter, wow x100!!!
Remi

-- 
Sent with K-9 Mail.

**Comment by guilhemmarchand** [comment]
@remg427 

With pleasure ;-) Yeah TrackMe is a very serious thing that provides incredibly valuable monitoring of your Splunk data, it will keep you busy some time for the good!

Cheers!

**Comment by guilhemmarchand** [comment]
@remg427 

The binary .tgz of the Splunk app resulting from the release is not to be stored in Git.
I am using the following process:

- While developing, run the build/build.sh to generate a safe and good practices compliant TGZ archive of the app
- When the release is ready to be published, I run the build/build.sh again, and take note of the SHA-256 that is produced
- Once changes are merged to the master branch, a new tag release is published in Git and the TGZ is attached in addition with the SHA-256 that was generated for this package (If unit testing of CircleCI calling Appinspect is passed)

You do not need to include the TGZ, you can get rid of it please ;-)
I will try to document the release processed in the pre-defined PR form.

Thanks!

**Comment by remg427** [comment]
sorry removed TGZ and will follow your guidelines for my apps as well. thanks
for jirarest I am not sure it is possible to use at same time auth= and headers= .
if not it might be required to convert username/password as an Authorization key in headers.

**Comment by guilhemmarchand** [comment]
@remg427 
Looking great! 
I am reviewing it, and will check for the auth header, the way I was using was working fine (thus I was looking in the future at what more robust forme of authentication the TA could be using in regard with what Jira could offer) but I will double check to make sure I understand your point here.
Will follow up shortly

**Comment by guilhemmarchand** [comment]
My apologises @remg427 I've been a bit late.
Will look at it later today and merge if everything works fine ;-) 
Thanks!

**Pull request merged**
